services:
  redis:
    image: redis:7-alpine
    container_name: neurodevops-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  neurodevops-collector:
    build: ./collector
    container_name: neurodevops-collector
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

  neurodevops-ai_engine:
    build: ./ai_engine
    container_name: neurodevops-ai_engine
    ports:
      - "11434:11434"
    restart: unless-stopped

  neurodevops-dashboard:
    build: ./dashboard
    container_name: neurodevops-dashboard
    depends_on:
      - neurodevops-collector
      - neurodevops-ai_engine
    ports:
      - "3000:3000"
    restart: unless-stopped

  ws_proxy:
    build: ./ws_proxy
    container_name: neurodevops-ws_proxy
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WS_PORT=4000
    ports:
      - "4000:4000"
    restart: unless-stopped

