services:
   neurodevops-collector:
    build: ./collector
    environment:
      - REDIS_HOST=neurodevops-redis
      - REDIS_PORT=6379
      - PUBLISH_INTERVAL=5
    depends_on:
      - neurodevops-redis
    # ...
  neurodevops-redis:
    image: redis:alpine
    # ...

  neurodevops-collector:
    build: ./collector
    container_name: neurodevops-collector
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

  neurodevops-ai_engine:
    build: ./ai_engine
    container_name: neurodevops-ai_engine
    ports:
      - "11434:11434"
    networks:
      default:
        aliases:
          - ai_engine

  neurodevops-dashboard:
    build: ./dashboard
    container_name: neurodevops-dashboard
    depends_on:
      - neurodevops-collector
      - neurodevops-ai_engine
    ports:
      - "3000:3000"
    restart: unless-stopped

  ws_proxy:
    build: ./ws_proxy
    container_name: neurodevops-ws_proxy
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WS_PORT=4000
    ports:
      - "4000:4000"
    restart: unless-stopped

