version: "3.9"

services:
  ai_engine:
    build:
      context: ./ai_engine
    container_name: neurodevops-ai
    restart: unless-stopped
    expose:
      - 11434
   collector:
     build:
      context: ./collector
    depends_on:
      - ai_engine
    restart: unless-stopped
  
    depends_on:
      - ollama_host
    environment:
      - OLLAMA_API=http://host.docker.internal:11434/api/generate
    restart: unless-stopped
