version: "3.8"

services:
  ai_engine:
    build:
      context: ./ai_engine
    container_name: neurodevops-ai_engine
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama  # <== Persist models here

  dashboard:
    build:
      context: ./dashboard
    container_name: neurodevops-dashboard
    ports:
      - "8080:8080"

  collector:
    build:
      context: ./collector
    container_name: neurodevops-collector

volumes:
  ollama_models:
