version: "3.8"

services:
  ai_engine:
    image: neurodevops-ai_engine
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama  # <== Persist models here

  dashboard:
    image: neurodevops-dashboard
    ports:
      - "8080:8080"

  collector:
    image: neurodevops-collector

volumes:
  ollama_models:
