version: "3.9"

services:
  ai_engine:
    build:
      context: ./ai_engine
    container_name: neurodevops-ai
    restart: unless-stopped
    expose:
      - "11434"

  collector:
    build:
      context: ./collector
    depends_on:
      - ai_engine
    restart: unless-stopped

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "8080:8080"
    restart: unless-stopped
