name: Deploy NeuroDevOps Stack

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Navigate to repo folder
        run: cd ${{ github.workspace }}

      - name: Build and restart containers
        run: |
          docker compose down
          docker compose up --build -d
